-- Setsuna_GreatPeopleSchoolIdol
-- Author: shigure
-- DateCreated: 5/19/2022 12:01:18 AM
--------------------------------------------------------------
INSERT INTO Types
	(Type, Kind)
VALUES
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI1',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI2',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI3',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI4',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI5',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI6',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI7',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI8',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI9',	'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI10', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI11', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI12', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI13', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI14', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI15', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI16', 'KIND_GREAT_PERSON_INDIVIDUAL'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI17', 'KIND_GREAT_PERSON_INDIVIDUAL');

	INSERT INTO GreatPersonIndividuals
	(GreatPersonIndividualType, Name, GreatPersonClassType, EraType, ActionCharges, Gender)
VALUES
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI1',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME1',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_RENAISSANCE',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI2',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME2',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_RENAISSANCE',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI3',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME3',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_RENAISSANCE',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI4',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME4',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_RENAISSANCE',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI5',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME5',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_INDUSTRIAL',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI6',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME6',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_INDUSTRIAL',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI7',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME7',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_INDUSTRIAL',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI8',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME8',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_INDUSTRIAL',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI9',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME9',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_MODERN',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI10',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME10',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_MODERN',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI11',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME11',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_MODERN',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI12',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME12',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_MODERN',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI13',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME13',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_ATOMIC',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI14',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME14',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_ATOMIC',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI15',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME15',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_ATOMIC',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI16',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME16',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_ATOMIC',	0,	'F'),
	('GREAT_PERSON_INDIVIDUAL_NIJIGASAKI17',	'LOC_GREAT_PERSON_INDIVIDUAL_NIJIGASAKI_NAME17',	'GREAT_PERSON_CLASS_SCHOOL_IDOL',	'ERA_INFORMATION',	0,	'F');